version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
  gradle: circleci/gradle@2.2.0
  eventuate-gradle-build-and-test: eventuate_io/eventuate-gradle-build-and-test@0.2.1
  orb-tools: circleci/orb-tools@10

#config_env: &config_env
#  environment:
#    JAVA_HOME: "/usr/lib/jvm/java-11-openjdk-amd64"

jobs:
  job_deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          name: Check if Heroku is installed
          command: |
            if [[ $(command -v heroku) == "" ]]; then
             echo "Heroku is not installed!"; exit 1;
            else
             echo Heroku successfully installed.
            fi
      - heroku/check-authentication
      - run:
          command: >
            echo "The command above installs Heroku, the command below deploys.
            What you do inbetween is up to you!"
      - heroku/deploy-via-git:
          force: true
          app-name: stock-price-alerter

  job_run_tests:
    executor: heroku/default
    # <<: *config_env
    steps:
      - checkout
      - heroku/install
      - run:
          name: Check if Heroku is installed
          command: |
            if [[ $(command -v heroku) == "" ]]; then
             echo "Heroku is not installed!"; exit 1;
            else
             echo Heroku successfully installed.
            fi
      - heroku/check-authentication
      # - run: chmod +x gradlew
      - run: ./gradlew dependencies
      - eventuate-gradle-build-and-test/build-and-test:
          name: Run tests
          project_name: test-orb
          script: ./gradlew :test
      #- run:
      #    name: Run tests
      #    command: ./gradlew :test
      # - store_test_results:
      #     path: test-results
      # - store_artifacts:
      #     path: test-results
      #     destination: reports/

filter_tag_version_only: &filter_tag_version_only
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/

workflows:
  heroku_deploy:
    jobs:
      - job_deploy:
          <<: *filter_tag_version_only

  run_tests:
    jobs:
      - job_run_tests